repos:
-   repo: https://github.com/united-minecrafters/kaede/
    rev: v2.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
