---
prefixes:
  - "!"
  - "hey, kaede "

kaedemojis:
  - <:cutie:718656585211314298>
  - <:cutie:716094809680379947>

no-table-flip:
  - "You could have hurt someone ):"
  - "Put it back!"
  - "Stoppppppppp"
  - "***NO***"
