---
channels:
  # info
  greeting:                       599974490662764545
  updates:                        600017035740839986
  rules:                          600014362719158297
  roles:                          603028701730308135
  polls:                          605457435288797248
  suggestions:                    599977968504274964
  mcupdates:                      637001831687520275
  unverified:                     691510005664448552

  #no mic
  overworld_nomic:   &OWNM        605531161841762429
  nether_nomic:      &NTNM        608395921687838741
  blaze_nomic:       &BZNM        605530852805443585
  zombie_nomic:      &ZMNM        605530918802948129
  ghast_nomic:       &GHNM        605531549626007555

  # general
  intro:                          669604332311937074
  starboard:                      694457589831827457
  bump:                           599973522143445022
  xchat:                          643519468928237568
  general:                        586199960198971418
  looking:                        682331164567928846
  degeneracy:                     692082377740124181
  movie:                          700812979586728037
  chatterboxes:                   707693664733888664

  # servers
  bedrocksvr:                     616003690616061963
  javasvr:                        682330791660748810

  # media
  showcase:                       601927482270023682
  art:                            611182729215606785
  photography:                    611182891770314762
  advertising:                    600351761324310538
  selfiesirl:                     611185362454315018
  pets:                           618258886205636639
  mediadump:                      606306207942180924
  memes:                          617273148391424010

  # bot stuff
  jukebox:                        605934083872129117
  botspam:                        599975909562253322

  # admin
  admin:           &ADMIN         600016557082673162
  staff:           &STAFF         600016613491736585
  kaede:           &KAEDE         715789040686727180
  modlog:                         608069216532168706
  log:                            599972200052817951
  adminbotspam:    &ADMIN_BOT     599966604805275660

  vcpairs:
    - vc: 586199960198971428
      ch: *OWNM
    - vc: 600666074295304193
      ch: *BZNM
    - vc: 605531394155872262
      ch: *GHNM
    - vc: 600483587967549443
      ch: *ZMNM
    - vc: 608395638823976980
      ch: *NTNM

roles:
  staff:    &STAFF_ROLE      608403610551713880
  owner:    &OWNER_ROLE      586236301355909123
  admin:    &ADMIN_ROLE      599975980492259328
  mod:      &MOD_ROLE        599976133781356565
  jr_mod:   &JR_MOD_ROLE     608784604588933130
  booster:                   669584239301492748
  muted:    &MUTED_ROLE      599966894069514251

prefixes:
  - &KAEDE_PREFIX "!"
  - "hey, kaede "

kaedemojis:
  - <:cutie:718656585211314298>
  - <:cutie:716094809680379947>

no-table-flip:
  - "You could have hurt someone ):"
  - "Put it back!"
  - "Stoppppppppp"
  - "***NO***"

filters:
  channel_whitelist:
    - *ADMIN
    - *ADMIN_BOT
    - *KAEDE
    - *STAFF
  word_blacklist:
    - goo+ks*
    - ky+s+
    - ki+ke+s*
    - beaner+s?
    - coo+ns*
    - nig+lets*
    - slant-eyes*
    - towe?l-?head+s*
    - chi*n+k+s*
    - spick*s*
    - kill* +(?:yo)?urself+
    - jew+s*
    - (re+)tar+(d+|t+)(ed)?
    - ta+r+d+
    - cunts*
    - trann*y
    - fuck(?:er)?

  token_blacklist:
    - fa+g+s*
    - cuck(?!oo+)
    - nigg+(?:e*r+|a+h*?|u+h+)s?
    - fag+o+t+s*

  domain_blacklist:
    - pornhub.com
    - liveleak.com
    - grabify.link
    - bmwforum.co
    - leancoding.co
    - spottyfly.com
    - stopify.co
    - yoütu.be
    - discörd.com
    - minecräft.com
    - freegiftcards.co
    - disçordapp.com
    - fortnight.space
    - fortnitechat.site
    - joinmy.site
    - curiouscat.club
    - catsnthings.fun
    - yourtube.site
    - youtubeshort.watch
    - catsnthing.com
    - youtubeshort.pro
    - canadianlumberjacks.online
    - poweredbydialup.club
    - poweredbydialup.online
    - poweredbysecurity.org
    - poweredbysecurity.online
    - ssteam.site
    - steamwalletgift.com
    - discord.gift

  role_whitelist:
    - *OWNER_ROLE
    - *ADMIN_ROLE
    - *JR_MOD_ROLE
    - *MOD_ROLE
    - *STAFF_ROLE

  guild_invite_whitelist:
    - 586199960198971409 # united
    - 673045897172746260 # autumn
    - 523136895245615124 # sturdy

logging:
  ignore_del_prefix:
    - "." # nadeko
    - "%" # ansura
    - *KAEDE_PREFIX
  ignore_bot: 1
